# Generated by Django 3.2.3 on 2021-05-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210526_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['id'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
    ]
